[book]
authors = ["Morg"]
language = "ja"
src = "src"
title = "Yokubi"

[output.html]
default-theme = "Navy"
additional-js = ["js/lunr.stemmer.support.js", "js/tinyseg.js", "js/lunr.jp.js", "js/lunr.multi.js", "js/load-lunr-plugin.js", "js/llm-sidebar.js"]
additional-css = ["style/custom.css"]
no-section-label = true

[output.html.fold]
enable = true

[output.html.search]
use-boolean-and = true   # multiple search terms combined with AND opposed to OR

[preprocessor.copy-system-prompt]
command = "/usr/bin/python3 scripts/copy-system-prompt.py"
renderers = ["html"]
before = ["furigana"]

[preprocessor.furigana]
command = "/usr/bin/python3 scripts/preprocess-furigana.py"
renderers = ["html"]
